// Main interface representing a single True/False trivia question
// Aligns with the 'trivia_true_false' table schema
export interface TrueFalseTrivia {
  id: number;
  question_text: string;
  is_true: boolean;
  explanation?: string | null;
  category?: string | null;
  theme?: string | null;
  difficulty?: string | null;
  tags?: string[] | null;
  attribution?: string | null;
  status?: string | null;
  used_in?: string[] | null;
  source_content_id?: number | null;
  display_order?: number | null;
  created_at: string;
  updated_at: string;
  published_at?: string | null;
  archived_at?: string | null;
}

// Type for creating a new True/False trivia question
// Omits fields that are auto-generated by the database
export type TrueFalseTriviaCreateInput = Omit<
  TrueFalseTrivia,
  "id" | "created_at" | "updated_at"
>;

// Type for updating an existing True/False trivia question
// All fields are optional for partial updates
export type TrueFalseTriviaUpdateInput = Partial<TrueFalseTriviaCreateInput>;

// Type for API query parameters when fetching a list of questions
export interface TrueFalseTriviaFetchParams {
  limit?: number;
  offset?: number;
  status?: "draft" | "published" | "archived";
  category?: string;
  difficulty?: string;
  theme?: string;
  orderBy?: string;
  order?: "asc" | "desc";
}

// Type for a standardized API response when fetching multiple questions
export interface TrueFalseTriviaApiResponse {
  data: TrueFalseTrivia[];
  total: number;
  limit: number;
  offset: number;
}
