import type { ProcessBuilderMetadata } from "./types";

// Cache for discovered process builders
let discoveredBuilders: Map<string, ProcessBuilderMetadata> | null = null;

/**
 * Auto-discover process builders by loading from generated registry
 * The registry is generated by the build script (scripts/discover-process-builders.ts)
 */
export async function discoverProcessBuilders(): Promise<
  Map<string, ProcessBuilderMetadata>
> {
  if (discoveredBuilders) {
    return discoveredBuilders;
  }

  discoveredBuilders = new Map();

  try {
    // Load from generated registry file
    // This file is generated at build time by the discovery script
    const registryModule = await import("../../process-builders-registry.json");
    const registry = registryModule.default || registryModule;

    for (const [id, metadata] of Object.entries(registry)) {
      discoveredBuilders.set(id, metadata as ProcessBuilderMetadata);
    }
  } catch (error) {
    console.warn("Failed to load process builders registry:", error);
    console.warn("Run: npm run discover-builders");
    // Fallback to empty registry - won't break the app
  }

  return discoveredBuilders;
}

/**
 * Get a specific process builder by ID
 */
export async function getProcessBuilder(
  id: string,
): Promise<ProcessBuilderMetadata | null> {
  const builders = await discoverProcessBuilders();
  return builders.get(id) || null;
}

/**
 * Get all discovered process builders
 */
export async function getAllProcessBuilders(): Promise<
  ProcessBuilderMetadata[]
> {
  const builders = await discoverProcessBuilders();
  return Array.from(builders.values());
}

/**
 * Register a process builder (for runtime registration if needed)
 */
export function registerProcessBuilder(metadata: ProcessBuilderMetadata): void {
  if (!discoveredBuilders) {
    discoveredBuilders = new Map();
  }
  discoveredBuilders.set(metadata.id, metadata);
}

/**
 * Clear the cache (useful for testing or hot reloading)
 */
export function clearRegistryCache(): void {
  discoveredBuilders = null;
}
