-- Add new columns to content table for enhanced structure
-- content_title: 3-4 word title generated by Gemini (all content types)
-- musings: The philosophical quote/thought (wisdom only)
-- from_the_box: The penalty box commentary (wisdom only)

ALTER TABLE content
ADD COLUMN IF NOT EXISTS content_title TEXT,
ADD COLUMN IF NOT EXISTS musings TEXT,
ADD COLUMN IF NOT EXISTS from_the_box TEXT;

-- Add comments for documentation
COMMENT ON COLUMN content.content_title IS '3-4 word title generated by Gemini for all content types';
COMMENT ON COLUMN content.musings IS 'Philosophical quote or thought - used by wisdom content type';
COMMENT ON COLUMN content.from_the_box IS 'Penalty box commentary - used by wisdom content type';

-- Note: content_text remains required for motivational, greetings, and stats
-- For wisdom, content_text is legacy; use musings + from_the_box instead

